Veterinaria/Controllers/PessoaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Veterinaria.DAO;
using Veterinaria.Models;

namespace Veterinaria.Controllers
{
    public class PessoaController : Controller
    {
        private PessoaDAO pessoas;
        private FuncionarioDAO funcionarios;

        private ClienteDAO clientes;
        private CidadeDAO cidades;

        private Connection connection;

        public PessoaController()
        {
            this.connection = new Connection();
            this.pessoas = new PessoaDAO(this.connection);
            this.funcionarios = new FuncionarioDAO(this.connection);
            this.clientes = new ClienteDAO(this.connection);
            this.cidades = new CidadeDAO(this.connection);
            this.connection.Close();
        }

        // GET: Pessoa
        public ActionResult Index()
        {
            return View(this.pessoas.ListAll());
        }

        // GET: Pessoa/Details/5
        public ActionResult Details(int id)
        {
            return View(this.pessoas.Search(new Pessoa { Id = id }));
        }

        // GET: Pessoa/Create
        public ActionResult Create()
        {
            return View(new Pessoa());
        }

        // POST: Pessoa/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                var pessoa = new Pessoa()
                {
                    Nome = collection["nome"],
                    Cpf = Util.RemoverCaracters(collection["Cpf"].ToString()),
                    DataNascimento = DateTime.Parse(collection["data_nascimento"]),
                    TelefoneFixo = Util.RemoverCaracters(collection["telefone_fixo"].ToString()),
                    TelefoneCelular = Util.RemoverCaracters(collection["telefone_celular"].ToString()),
                    Endereco = collection["endereco"],
                    Bairro = collection["bairro"],
                    Complemento = collection["complemento"]
                };

                if (!String.IsNullOrEmpty(collection["numero"]))
                    pessoa.Numero = int.Parse(collection["numero"]);

                if (!String.IsNullOrEmpty(collection["email"]))
                    pessoa.Cliente = new Cliente() { Email = collection["email"] };

                if (!String.IsNullOrEmpty(collection["numerocontrato"]) && !String.IsNullOrEmpty(collection["salario"]) && !String.IsNullOrEmpty(collection["data_admissao"]) && !String.IsNullOrEmpty(collection["setor"]))
                {
                    pessoa.Funcionario = new Funcionario()
                    {
                        NumeroContrato = collection["numerocontrato"],
                        NumeroCRMV = collection["numerocrmv"],
                        Salario = double.Parse(collection["salario"]),
                        DataAdmisao = DateTime.Parse(collection["data_admissao"]),
                        Funcao = (Models.Enums.FuncaoFuncionario)int.Parse(collection["setor"])
                    };
                }

                if (!String.IsNullOrEmpty(collection["Idcidade"]))
                    pessoa.Cidade = new Cidade() { Id = int.Parse(collection["Idcidade"]) };
                else
                {
                    ViewBag.Erro = "Cidade Inválida";
                    return View(pessoa);
                }

                if (pessoas.Search(new Pessoa { Cpf = Util.RemoverCaracters(collection["Cpf"].ToString()) }) != null)
                {
                    ViewBag.Erro = "Pessoa Ja Cadastrada";
                    return View(pessoa);
                }

                if (pessoa.Funcionario == null && pessoa.Cliente == null)
                {
                    ViewBag.Erro = "E necessario Preencher os dados de Cliente ou Funcionario";
                    return View(pessoa);
                }

                if (pessoa.Cliente != null)
                    pessoa.Cliente.Id = (int)clientes.Insert(pessoa.Cliente);

                if (pessoa.Funcionario != null)
                    pessoa.Funcionario.Id = (int)funcionarios.Insert(pessoa.Funcionario);

                this.pessoas.Insert(pessoa);
                return RedirectToAction("Index");
            }
            catch (Exception) { return View(new Pessoa()); }
        }

        // GET: Pessoa/Edit/5
        public ActionResult Edit(int id)
        {
            return View(this.pessoas.Search(new Pessoa { Id = id }));
        }

        // POST: Pessoa/Edit/5
        [HttpPost]
        public ActionResult Edit(FormCollection collection)
        {
            try
            {
                var pessoa = new Pessoa()
                {
                    Id = int.Parse(collection["idpessoa"]),
                    Nome = collection["nome"],
                    Cpf = Util.RemoverCaracters(collection["Cpf"].ToString()),
                    DataNascimento = DateTime.Parse(collection["data_nascimento"]),
                    TelefoneFixo = Util.RemoverCaracters(collection["telefone_fixo"].ToString()),
                    TelefoneCelular = Util.RemoverCaracters(collection["telefone_celular"].ToString()),
                    Endereco = collection["endereco"],
                    Bairro = collection["bairro"],
                    Complemento = collection["complemento"]
                };

                if (!string.IsNullOrEmpty(collection["numero"]))
                    pessoa.Numero = int.Parse(collection["numero"]);

                if (!String.IsNullOrEmpty(collection["email"]))
                {
                    pessoa.Cliente = new Cliente() { Email = collection["email"] };
                    if (!String.IsNullOrEmpty(collection["idcliente"]))
                    {
                        pessoa.Cliente.Id = int.Parse(collection["idcliente"]);
                        this.clientes.Update(pessoa.Cliente);
                    }
                    else
                        pessoa.Cliente.Id = (int)this.clientes.Insert(pessoa.Cliente);
                }
                if (!String.IsNullOrEmpty(collection["numerocontrato"]) && !String.IsNullOrEmpty(collection["salario"]) && !String.IsNullOrEmpty(collection["data_admissao"]) && !String.IsNullOrEmpty(collection["setor"]))
                {
                    pessoa.Funcionario = new Funcionario()
                    {
                        NumeroContrato = collection["numerocontrato"],
                        NumeroCRMV = collection["numerocrmv"],
                        Salario = double.Parse(collection["salario"]),
                        DataAdmisao = DateTime.Parse(collection["data_admissao"]),
                        Funcao = (Models.Enums.FuncaoFuncionario)int.Parse(collection["setor"])
                    };
                    if (!String.IsNullOrEmpty(collection["idfuncionario"]))
                    {
                        pessoa.Funcionario.Id = int.Parse(collection["idfuncionario"]);
                        this.funcionarios.Update(pessoa.Funcionario);
                    }
                    else
                        pessoa.Funcionario.Id = (int)this.funcionarios.Insert(pessoa.Funcionario);
                }
                if (!String.IsNullOrEmpty(collection["Idcidade"]))
                    pessoa.Cidade = new Cidade() { Id = int.Parse(collection["Idcidade"]) };

                this.pessoas.Update(pessoa);
                return RedirectToAction("Index");
            }
            catch (Exception) { return View(); }
        }

        // GET: Pessoa/Delete/5
        public ActionResult Delete(int id)
        {
            this.pessoas.Delete(new Pessoa { Id = id });
            return RedirectToAction("Index");
        }

        // POST: Pessoa/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                this.pessoas.Delete(new Pessoa { Id = id });
                return RedirectToAction("Index");
            }
            catch { return View(); }
        }

        public ActionResult ListarCidadesAutocomplete(string filtro)
        {
            return Json(this.cidades.ListFiltro(filtro).Select(item => new
            {
                data = item.Id,
                value = item.Nome
            }).ToArray(), JsonRequestBehavior.AllowGet);
        }
    }
}

Veterinaria/Controllers/PetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Veterinaria.DAO;
using Veterinaria.Models;

namespace Veterinaria.Controllers
{
    public class PetController : Controller
    {
        private PetDAO pets;
        private PessoaDAO pessoas;

        private ClienteDAO clientes;

        private Connection connection;

        public PetController()
        {
            this.connection = new Connection();
            this.pets = new PetDAO(this.connection);
            this.pessoas = new PessoaDAO(this.connection);
            this.clientes = new ClienteDAO(this.connection);
        }

        // GET: Pet
        public ActionResult Index()
        {
            return View(this.pets.ListAll());
        }

        // GET: Pet/Details/5
        public ActionResult Details(int id)
        {
            return View(this.pets.Search(new Pet { Id = id }));
        }

        // GET: Pet/Create
        public ActionResult Create()
        {
            var pet = new Pet();
            pet.ListaClientes = GetClientes();
            return View(pet);
        }
        private IEnumerable<SelectListItem> GetClientes()
        {
            var listaClientes = this.pessoas.ListAllClientes().Select(x =>
                                new SelectListItem
                                {
                                    Value = x.Cliente?.Id.ToString(),
                                    Text = x.Nome
                                });

            return new SelectList(listaClientes, "Value", "Text");
        }

        // POST: Pet/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                this.pets.Insert(new Pet
                {
                    Nome = collection["nome"].ToString(),
                    DataNascimento = DateTime.Parse(collection["data_nascimento"]),
                    Raca = collection["raca"].ToString(),
                    Sexo = int.Parse(collection["sexo"]),
                    Tipo = int.Parse(collection["tipo"]),
                    Cliente = new Pessoa() { Cliente = new Cliente() { Id = int.Parse(collection["idcliente"]) } }
                });
                return RedirectToAction("Index");
            }
            catch (Exception) { return View(); }
        }

        // GET: Pet/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Pet/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                this.pets.Update(new Pet
                {
                    Id = int.Parse(collection["id"]),
                    Nome = collection["nome"].ToString(),
                    DataNascimento = DateTime.Parse(collection["data_nascimento"]),
                    Raca = collection["raca"],
                    Sexo = int.Parse(collection["sexo"]),
                    Tipo = int.Parse(collection["tipo"]),
                    Cliente = new Pessoa() { Cliente = new Cliente() { Id = int.Parse(collection["idcliente"]) } }
                });
                return RedirectToAction("Index");
            }
            catch { return View(); }
        }

        // GET: Pet/Delete/5
        public ActionResult Delete(int id)
        {
            this.pets.Delete(new Pet { Id = id });
            return RedirectToAction("Index");
        }

        // POST: Pet/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                this.pets.Delete(new Pet { Id = id });
                return RedirectToAction("Index");
            }
            catch { return View(); }
        }
    }
}

Veterinaria/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Veterinaria.DAO;
using Veterinaria.Models;

namespace Veterinaria.Controllers
{
    public class ProdutoController : Controller
    {
        private ProdutoDAO produtos;

        public ProdutoController()
        {
            this.produtos = new ProdutoDAO(new Connection());
        }

        // GET: Produto
        public ActionResult Index()
        {
            ViewBag.Message = "Produtos";
            return View(this.produtos.ListAll());
        }

        // GET: Produto/Details/5
        public ActionResult Details(int id)
        {
            return View(this.produtos.Search(new Produto { IdProduto = id }));
        }

        // GET: Produto/Create
        public ActionResult Create()
        {
            return View(new Produto());
        }

        // POST: Produto/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                var produto = new Produto
                {
                    Nome = collection["nome"].ToString(),
                    Descricao = collection["descricao"].ToString(),
                    Valor = int.Parse(collection["valor"]),
                    Qtd_Estoque = int.Parse(collection["qtdestoque"])
                };
                this.produtos.Insert(produto);
                return RedirectToAction("Index");
            }
            catch { return View(); }
        }

        // GET: Produto/Edit/5
        public ActionResult Edit(int id)
        {
            return View(this.produtos.Search(new Produto { IdProduto = id }));
        }

        // POST: Produto/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                var produto = new Produto
                {
                    IdProduto = int.Parse(collection["idproduto"]),
                    Nome = collection["nome"].ToString(),
                    Descricao = collection["descricao"].ToString(),
                    Valor = int.Parse(collection["valor"]),
                    Qtd_Estoque = int.Parse(collection["qtdestoque"])
                };
                this.produtos.Update(produto);
                return RedirectToAction("Index");
            }
            catch { return View(); }
        }

        // GET: Produto/Delete/5
        public ActionResult Delete(int id)
        {
            return View(this.produtos.Delete(new Produto { IdProduto = id }));
        }

        // POST: Produto/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                this.produtos.Delete(new Produto { IdProduto = id });
                return RedirectToAction("Index");
            }
            catch { return View(); }
        }
    }
}

Veterinaria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
   

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@ViewBag.Title </title>

    <!-- Bootstrap core CSS -->
    @Styles.Render("~/Vendors/bootstrap/dist/css/bootstrap.min.css")
    @Styles.Render("~/Vendors/font-awesome/css/font-awesome.min.css")
    @Styles.Render("~/Vendors/nprogress/nprogress.css")
    @Styles.Render("~/Content/custom.min.css")

    <!--[if lt IE 9]>
    <script src="../assets/js/ie8-responsive-file-warning.js"></script>
    <![endif]-->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 menu_fixed left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="@Url.Action("Index", "Home")" class="site_title"><i class="fa fa-paw"></i> <span>Veterinaria</span></a>
                    </div>
                    <div class="clearfix"></div>
                  
                    <!-- /menu profile quick info -->
                    <br />
                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3>Cadastro</h3>
                            <ul class="nav side-menu">
                                <li>
                                    <a><i class="fa fa-group"></i> Pessoa <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li>@Html.ActionLink("Cadastrar", "Create", "Pessoa")</li>
                                        <li>@Html.ActionLink("Listar", "Index", "Pessoa")</li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-cubes"></i> Produto <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li>@Html.ActionLink("Cadastrar", "Create", "Produto")</li>
                                        <li>@Html.ActionLink("Listar", "Index", "Produto")</li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-bug"></i> Pet <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li>@Html.ActionLink("Cadastrar", "Create", "Pet")</li>
                                        <li>@Html.ActionLink("Listar", "Index", "Pet")</li>    
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="menu_section">
                            <h3>Operações</h3>
                            <ul class="nav side-menu">
                                <li>
                                    <a><i class="fa fa-calendar"></i> Consulta <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li>@Html.ActionLink("Nova", "Create", "Consulta")</li>
                                        <li>@Html.ActionLink("Listar", "Index", "Consulta")</li>   
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-money"></i> Venda <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">                              
                                        <li>@Html.ActionLink("Nova", "Create", "Venda")</li>
                                        <li>@Html.ActionLink("Listar", "Index", "Venda")</li>                                      
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /sidebar menu -->
                
                </div>
            </div>
            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <img src="../images/user.png" alt="">Usuario
                                  
                                </a>
                            
                            </li>
                       
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->


            <div class="right_col" role="main">
                @RenderBody()
               
            </div>
            <footer>
                <div class="pull-right">
                   @DateTime.Now.Year
                </div>
                <div class="clearfix"></div>
            </footer>
        </div>
    </div>


            <!-- jQuery -->
            @Scripts.Render("~/Vendors/jquery/dist/jquery.min.js")

            @Scripts.Render("~/Vendors/bootstrap/dist/js/bootstrap.min.js")

            @Scripts.Render("~/Vendors/fastclick/lib/fastclick.js")

            @Scripts.Render("~/Vendors/nprogress/nprogress.js")

            @Scripts.Render("~/Scripts/custom.min.js")

    @RenderSection("scripts", required: false)

</body>
</html>