Veterinaria/Models/Consulta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Veterinaria.Models.Enums;

namespace Veterinaria.Models
{
    public class Consulta
    {
        public int Id { get; set; }
        public DateTime Data { get; set; }
        public StatusConsulta Status { get; set; }
        public Pet Pet { get; set; }
        public Pessoa Atendente { get; set; }
        public Pessoa Veterinario { get; set; }
        public Diagnostico Diagnostico { get; set; }
    }
}

Veterinaria/Controllers/ConsultaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Veterinaria.DAO;
using Veterinaria.Models;
using Veterinaria.Models.Enums;

namespace Veterinaria.Controllers
{
    public class ConsultaController : Controller
    {
        private PetDAO pets;
        private PessoaDAO pessoas;

        private ConsultaDAO consultas;
        private Connection connection;

        private DiagnosticoDAO diagnosticos;

        public ConsultaController()
        {
            this.connection = new Connection();
            this.pets = new PetDAO(this.connection);
            this.pessoas = new PessoaDAO(this.connection);
            this.consultas = new ConsultaDAO(this.connection);
            this.diagnosticos = new DiagnosticoDAO(this.connection);
        }

        // GET: Consulta
        public ActionResult Index()
        {
            ViewBag.Message = "Consultas";
            return View(this.consultas.ListAll());
        }

        // GET: Consulta/Details/5
        public ActionResult Details(int id)
        {
            return View(this.consultas.Search(new Consulta { Id = id }));
        }

        // GET: Consulta/Create
        public ActionResult Create()
        {
            var consulta = new Consulta();
            consulta.Data = DateTime.Today;
            return View(consulta);
        }

        // POST: Consulta/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                this.consultas.Insert(new Consulta
                {
                    Data = DateTime.Parse(collection["data"]),
                    Status = (StatusConsulta)int.Parse(collection["status"]),
                    Pet = this.pets.Search(new Pet() { Id = int.Parse(collection["idpet"]) }),
                    Veterinario = new Pessoa() { Funcionario = new Funcionario() { Id = int.Parse(collection["idveterinario"]) } },
                    Atendente = new Pessoa() { Funcionario = new Funcionario() { Id = int.Parse(collection["idatendente"]) } }
                });
                return RedirectToAction("Index");
            }
            catch (Exception) { return View(new Consulta()); }
        }

        // GET: Consulta/Edit/5
        public ActionResult Edit(int id)
        {
            return View(this.consultas.Search(new Consulta { Id = id }));
        }

        // POST: Consulta/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            Consulta consulta = new Consulta();
            try
            {
                this.consultas.Update(consulta = new Consulta {
                    Id = int.Parse(collection["idconsulta"]),
                    Data = DateTime.Parse(collection["data"]),
                    Status = (StatusConsulta)int.Parse(collection["status"]),
                    Pet = this.pets.Search(new Pet() { Id = int.Parse(collection["idpet"]) }),
                    Veterinario = this.pessoas.Search(new Pessoa() { Funcionario = new Funcionario() { Id = int.Parse(collection["idveterinario"]) } }),
                    Atendente = this.pessoas.Search(new Pessoa() { Funcionario = new Funcionario() { Id = int.Parse(collection["idatendente"]) } }),
                    Diagnostico = new Diagnostico() { Id = int.Parse(collection["iddiagnostico"]),
                                                      Posologia = collection["posologia"],
                                                      Medicacao = collection["medicacao"],
                                                      Descricao = collection["descricao"] }
                });
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ViewBag.Erro = ex.Message;
                return View(consulta);
             }
        }

        // GET: Consulta/Delete/5
        public ActionResult Delete(int id)
        {
            this.consultas.Delete(new Consulta { Id = id });
            return RedirectToAction("Index");
        }

        // POST: Consulta/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                this.consultas.Delete(new Consulta { Id = id });
                return RedirectToAction("Index");
            }
            catch { return View(); }
        }

        public ActionResult ListarPets()
        {
            return Json(this.pets.ListAll().Select(item => new
            {
                data = item.Id,
                value = item.Cliente.Nome + " - " + item.Nome
            }).ToArray(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult ListarAtendentes()
        {
            return Json(this.pessoas.ListAllFuncionarios()
                .Where(pessoa => pessoa.Funcionario.Funcao == FuncaoFuncionario.Atendente)
                .Select(item => new
                {
                    data = item.Funcionario?.Id,
                    value = item.Nome
                }).ToArray(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult ListarVeterinarios()
        {
            return Json(this.pessoas.ListAllFuncionarios()
                .Where(pessoa => pessoa.Funcionario.Funcao == FuncaoFuncionario.Veterinario)
                .Select(item => new
                {
                    data = item.Funcionario?.Id,
                    value = item.Nome
                }).ToArray(), JsonRequestBehavior.AllowGet);
        }
    }
}

Veterinaria/Views/Consulta/Create.cshtml
@using Veterinaria.Models

@model Consulta
@{
    ViewBag.Title = "Cadastro de Consultas";
    ViewBag.Diagnostico = "Cadastro de Diagnostico";

    if (!String.IsNullOrEmpty(ViewBag.Erro))
    {
        <script>alert("@ViewBag.Erro");</script>
    }
}

<div class="col-md-12">
    <form method="post">
        <div class="x_panel">
            <div class="x_title">
                <h2>@ViewBag.Title</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li class="pull-right">
                        <a class="collapse-link pull-right"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="col-xs-12 col-sm">
                    <div class="block col-sm">
                        <div class="block-content">
                            <div class="row row-form">
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        @Html.Label("Data")
                                        <div class="xdisplay_inputx form-group has-feedback">
                                            <input type="text" class="form-control has-feedback-left" name="data" id="data" value="@Model.Data" placeholder="First Name" aria-describedby="inputSuccess2Status2">
                                            <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
                                            <span id="inputSuccess2Status2" class="sr-only">(success)</span>

                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-3">
                                    <div class="form-group">
                                        @Html.Label("Status")
                                        <select id="status" class="form-control" name="status">
                                            <option selected="selected" value="0">Agendada</option>
                                            <option value="1">Cancelada</option>
                                            <option value="2">Atendida</option>
                                        </select>
</div>
                                </div>
                            </div>
                            <div class="row row-form">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        @Html.Label("Cliente - Pet")
                                        <select id="idpet" class="form-control"  name="idpet">
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        @Html.Label("Atendente")
                                        <select id="idatendente" class="form-control"  name="idatendente">
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        @Html.Label("Veterinario")
                                        <select id="idveterinario" class="form-control"  name="idveterinario">
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
       
        <div class="x_panel" style="height: auto;">
            <div class="x_content">
                <div class="row row-form">
                    <div class="form-group">
                        <div class="col-md-12 col-sm-12 col-xs-12 pull-right">
                            <button type="submit" class="btn btn-success pull-right">Salvar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts 
{
    @Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/Scripts/moment/moment.min.js")
    @Scripts.Render("~/Scripts/datepicker/daterangepicker.js")

    <script>
        $(document).ready(function () {
            (function () {
                $.ajax({
                    url: '@Url.Action("ListarPets", "Consulta")',
                    data: '{}',
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (json) {
                        var clientes = $("#idpet");
                        clientes.empty().append('<option selected="selected" value="0">Por favor selecione</option>');
                        for (var i = 0; i < json.length; i++)
                            clientes.append('<option selected="selected" value=' + json[i].data + '>' + json[i].value + '</option>');
                    },
                    error: function (xmlHttpRequest, textStatus, errorThrown) {
                        console.log('some error occured', textStatus, errorThrown);
                    }
                });
            })();
            (function () {
                $.ajax({
                    url: '@Url.Action("ListarAtendentes", "Consulta")',
                    data: '{}',
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (json) {
                        var clientes = $("#idatendente");
                        clientes.empty().append('<option selected="selected" value="0">Por favor selecione</option>');
                        for (var i = 0; i < json.length; i++)
                            clientes.append('<option selected="selected" value=' + json[i].data + '>' + json[i].value + '</option>');
                    },
                    error: function (xmlHttpRequest, textStatus, errorThrown) {
                        console.log('some error occured', textStatus, errorThrown);
                    }
                });
            })();
            (function () {
                $.ajax({
                    url: '@Url.Action("ListarVeterinarios", "Consulta")',
                    data: '{}',
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (json) {
                        var clientes = $("#idveterinario");
                        clientes.empty().append('<option selected="selected" value="0">Por favor selecione</option>');
                        for (var i = 0; i < json.length; i++)
                            clientes.append('<option selected="selected" value=' + json[i].data + '>' + json[i].value + '</option>');
                    },
                    error: function (xmlHttpRequest, textStatus, errorThrown) {
                        console.log('some error occured', textStatus, errorThrown);
                    }
                });
            })();

            $('#data').daterangepicker({
                singleDatePicker: true,
                calender_style: "picker_4",
                format: 'DD/MM/YYYY',
            });

        });
    </script>
}

Veterinaria/Views/Consulta/Edit.cshtml
@using Veterinaria.Models

@model Consulta
@{
    ViewBag.Title = "Alterar Consulta";
    ViewBag.Diagnostico = "Cadastrar Diagnostico";
    if (!String.IsNullOrEmpty(ViewBag.Erro))
    {
        <script>alert("@ViewBag.Erro");</script>
    }
}

<div class="col-md-12">
    <form method="post">
        <div class="x_panel">
            <div class="x_title">
                <h2>@ViewBag.Title</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li class="pull-right">
                        <a class="collapse-link pull-right"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="col-xs-12 col-sm">
                    <div class="block col-sm">
                        <div class="block-content">
                            <div class="row row-form">
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        @Html.Label("Data")
                                        <div class="xdisplay_inputx form-group has-feedback">
                                            <input type="text" class="form-control has-feedback-left" name="data" id="data" value="@Model.Data" placeholder="First Name" aria-describedby="inputSuccess2Status2">
                                            <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
                                            <span id="inputSuccess2Status2" class="sr-only">(success)</span>
                                        </div>
                                        @Html.TextBox("idconsulta", Model.Id, new { id = "idconsulta", @class = "form-control hide" })
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        @Html.Label("Status")
                                        <select id="status" class="form-control" name="status">
                                            <option selected="selected" value="0">Agendada</option>
                                            <option value="1">Cancelada</option>
                                            <option value="2">Atendida</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row row-form">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        @Html.Label("Cliente / Pet")
                                        <select id="idpet" class="form-control" name="idpet"></select>
                                    </div>
                                    <div class="form-group">
                                        @Html.Label("Atendente")
                                        <select id="idatendente" class="form-control" name="idatendente"></select>
                                    </div>
                                    <div class="form-group">
                                        @Html.Label("Veterinario")
                                        <select id="idveterinario" class="form-control" name="idveterinario"></select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="x_panel" >
            <div class="x_title">
                <h2>@ViewBag.Diagnostico</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li class="pull-right">
                        <a class="collapse-link pull-right"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="col-xs-12 col-sm">
                    <div class="block col-sm">
                        <div class="block-content">
                            <div class="row row-form">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        @Html.Label("Posologia")
                                        @Html.TextBox("posologia", Model.Diagnostico?.Posologia, new { id = "posologia", @class = "form-control", @maxlength = 100 })
                                        @Html.TextBox("iddiagnostico", Model.Diagnostico?.Id, new { id = "iddiagnostico", @class = "form-control hide" })

                                     </div>
                                    <div class="form-group">
                                        @Html.Label("Medicação")
                                        @Html.TextBox("medicacao", Model.Diagnostico?.Medicacao, new { id = "medicacao", @class = "form-control", @maxlength = 100 })
                                    </div>
                                    <div class="form-group">
                                        @Html.Label("Descrição")
                                        @Html.TextBox("descricao", Model.Diagnostico?.Descricao, new { id = "descricao", @class = "form-control", @maxlength = 100 })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="x_panel" style="height: auto;">
            <div class="x_content">
                <div class="row row-form">
                    <div class="form-group">
                        <div class="col-md-12 col-sm-12 col-xs-12 pull-right">
                            <button type="submit" class="btn btn-success pull-right">Salvar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/moment/moment.min.js")
    @Scripts.Render("~/Scripts/datepicker/daterangepicker.js")

    <script>
        $(document).ready(function () {
            (function () {
                $.ajax({
                    url: '@Url.Action("ListarPets", "Consulta")',
                    data: '{}',
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (json) {
                        var clientes = $("#idpet");
                        clientes.empty().append('<option value="0">Por favor selecione</option>');
                        for (var i = 0; i < json.length; i++) {
                            if(json[i].data == @Model.Pet.Id)
                            clientes.append('<option selected="selected" value=' + json[i].data + '>' + json[i].value + '</option>');
                            else
                                clientes.append('<option  value=' + json[i].data + '>' + json[i].value + '</option>');

                        }
                    },
                    error: function (xmlHttpRequest, textStatus, errorThrown) {
                        console.log('some error occured', textStatus, errorThrown);
                    }
                });
            })();
            (function () {
                $.ajax({
                    url: '@Url.Action("ListarAtendentes", "Consulta")',
                    data: '{}',
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (json) {
                        var clientes = $("#idatendente");
                        clientes.empty().append('<option  value="0">Por favor selecione</option>');
             
                        for (var i = 0; i < json.length; i++){
                            if(json[i].data == @Model.Atendente.Funcionario.Id)
                                clientes.append('<option selected="selected" value=' + json[i].data + '>' + json[i].value + '</option>');
                            else
                                clientes.append('<option  value=' + json[i].data + '>' + json[i].value + '</option>');

                    }  },
                    error: function (xmlHttpRequest, textStatus, errorThrown) {
                        console.log('some error occured', textStatus, errorThrown);
                    }
                });
            })();
            (function () {
                $.ajax({
                    url: '@Url.Action("ListarVeterinarios", "Consulta")',
                    data: '{}',
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (json) {
                        var clientes = $("#idveterinario");
                        clientes.empty().append('<option value="0">Por favor selecione</option>');

                        for (var i = 0; i < json.length; i++)
                        {
                            if(json[i].data == @Model.Veterinario.Funcionario.Id)
                                clientes.append('<option selected="selected" value=' + json[i].data + '>' + json[i].value + '</option>');
                            else
                                clientes.append('<option  value=' + json[i].data + '>' + json[i].value + '</option>');

                        }
                },
                    error: function (xmlHttpRequest, textStatus, errorThrown) {
                        console.log('some error occured', textStatus, errorThrown);
                    }
                });
            })();
            $('#data').daterangepicker({
                singleDatePicker: true,
                calender_style: "picker_4",
                format: 'DD/MM/YYYY'
            });
        });
    </script>
}

Veterinaria/Views/Consulta/Index.cshtml
@using Veterinaria.Models

@model List<Consulta>
@{
    ViewBag.Title = "Listar Consultas";
}

<div class="col-md-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>@ViewBag.Title</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Data</th>
                        <th>Cliente - Pet</th>
                        <th>Atendente</th>
                        <th>Veterinario</th>
                        <th>Status</th>
                        <th>Opções</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Consulta objeto in Model)
                    {
                        <tr>
                            <td> @objeto.Id </td>
                            <td> @objeto.Data.ToString() </td>
                            <td> @objeto.Pet.Cliente.Nome - @objeto.Pet.Nome</td>
                            <td> @objeto.Atendente.Nome</td>
                            <td> @objeto.Veterinario.Nome</td>
                            <td> @objeto.Status.ToString()</td>
                            <td>
                                <a href="@Url.Action("Details", "Consulta")?id=@objeto.Id" }" class="btn btn-info">
                                    <span class="fa fa-file-o" aria-hidden="true"></span>
                                </a>

                                <a href="@Url.Action("Edit", "Consulta")?id=@objeto.Id" }" class="btn btn-warning" placeholder="Editar">
                                    <span class="fa fa-edit" aria-hidden="true"></span>
                                </a>

                                <a href="@Url.Action("Delete", "Consulta")?id=@objeto.Id" }" class="btn btn-danger">
                                    <span class="fa fa-warning" aria-hidden="true"></span>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section scripts 
{
    @Styles.Render("~/Vendors/datatables.net-bs/css/dataTables.bootstrap.min.css")
    @Styles.Render("~/Vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css")
    @Styles.Render("~/Vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css")

    @Scripts.Render("~/Vendors/datatables.net/js/jquery.dataTables.min.js")
    @Scripts.Render("~/Vendors/datatables.net-bs/js/dataTables.bootstrap.min.js")
    @Scripts.Render("~/Vendors/datatables.net-responsive/js/dataTables.responsive.min.js")
    @Scripts.Render("~/Vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js")
    @Scripts.Render("~/Vendors/datatables.net-scroller/js/datatables.scroller.min.js")

    <script>
        $(document).ready(function () {
            $('#datatable-responsive').DataTable();
        });
    </script>
}